// Generates the devops sandbox for a workspace: a docker-compose.yaml wiring one
// container per requested service and a .env of connection variables pointing at
// the workspace's isolated host ports. Pure string rendering — no Docker library,
// no filesystem — so it is fully unit-testable and the caller decides where to
// write. New capability: Orca had no container orchestration before this.
import type {
  StructuredServiceKind,
  StructuredWorkspaceService
} from '../../shared/structured-project-schema'

// Default credential for generated dev sandboxes. These are local-only,
// disposable databases, never production — the value is intentionally fixed so
// the generated .env is self-consistent.
const DEFAULT_DB_PASSWORD = 'orca'
const DEFAULT_DB_NAME = 'app'
const BIND_HOST = '127.0.0.1'

type ServiceDefinition = {
  image: string
  containerPort: number
  volumeMount: string
  environment: (password: string) => Record<string, string>
}

const SERVICE_DEFINITIONS: Record<StructuredServiceKind, ServiceDefinition> = {
  mysql: {
    image: 'mysql:8',
    containerPort: 3306,
    volumeMount: '/var/lib/mysql',
    environment: (password) => ({ MYSQL_ROOT_PASSWORD: password, MYSQL_DATABASE: DEFAULT_DB_NAME })
  },
  redis: {
    image: 'redis:7',
    containerPort: 6379,
    volumeMount: '/data',
    environment: () => ({})
  },
  postgres: {
    image: 'postgres:16',
    containerPort: 5432,
    volumeMount: '/var/lib/postgresql/data',
    environment: (password) => ({ POSTGRES_PASSWORD: password, POSTGRES_DB: DEFAULT_DB_NAME })
  },
  mongo: {
    image: 'mongo:7',
    containerPort: 27017,
    volumeMount: '/data/db',
    environment: (password) => ({
      MONGO_INITDB_ROOT_USERNAME: 'root',
      MONGO_INITDB_ROOT_PASSWORD: password
    })
  }
}

export type DevopsSandbox = {
  composeYaml: string
  envFile: string
}

function renderService(service: StructuredWorkspaceService, password: string): string {
  const def = SERVICE_DEFINITIONS[service.kind]
  const lines = [
    `  ${service.kind}:`,
    `    image: ${def.image}`,
    '    restart: unless-stopped',
    '    ports:',
    `      - "${service.hostPort}:${def.containerPort}"`
  ]
  const env = def.environment(password)
  const envEntries = Object.entries(env)
  if (envEntries.length > 0) {
    lines.push('    environment:')
    for (const [key, value] of envEntries) {
      lines.push(`      ${key}: ${value}`)
    }
  }
  lines.push('    volumes:', `      - ./data/${service.kind}:${def.volumeMount}`)
  return lines.join('\n')
}

function renderCompose(services: StructuredWorkspaceService[], password: string): string {
  const blocks = services.map((service) => renderService(service, password))
  return `services:\n${blocks.join('\n')}\n`
}

function renderEnv(services: StructuredWorkspaceService[]): string {
  const header = "# Generated by Orca: environment variables for this workspace's isolated sandbox"
  const lines = [header]
  for (const service of services) {
    const prefix = service.kind.toUpperCase()
    lines.push(`${prefix}_HOST=${BIND_HOST}`, `${prefix}_PORT=${service.hostPort}`)
  }
  return `${lines.join('\n')}\n`
}

export function generateDevopsSandbox(
  services: StructuredWorkspaceService[],
  options?: { password?: string }
): DevopsSandbox {
  const password = options?.password ?? DEFAULT_DB_PASSWORD
  return {
    composeYaml: renderCompose(services, password),
    envFile: renderEnv(services)
  }
}

// Container-internal ports, exposed so the scaffolder / tests can reason about
// the mapping without reaching into the private definition table.
export function containerPortFor(kind: StructuredServiceKind): number {
  return SERVICE_DEFINITIONS[kind].containerPort
}
